### ISSUE TITLE
will there be a version 1.11.2 update

### ISSUE THREAD

**Issue by darungon** [darkevilmac/archimedes-ships-plus#185] opened 2017-09-20 15:48 UTC
Thanks for reporting an issue to Teckle, an Elytra project!

When reporting an issue to an Elytra project, please make sure to include:

- The version of the mod you are using (e.g. 2.0.0a4)
- Your Minecraft version (e.g. 1.11.2)
- Your Forge version (e.g. 13.20.0.2252)
- The crash report or log, uploaded to gist.github.com
  (e.g. https://gist.github.com/unascribed/09ec875df0cc830df1116559f4adb333)

Do not say latest! Saying you are on the latest version of
something does not help us!

Never include crash reports in the issue body itself! They
are extremely long and it makes it difficult to read your issue.

Don't cherry pick parts of the log or crash report; send the
whole thing!

Avoid putting tags like [Bug] or [Feature Request] in your title;
that's what labels are for, and the maintainer will decide what
category your issue fits in.

Pastebin is acceptable for crash reports or logs, but Gist is
greatly preferred.

Please remove this help text after reading it and before posting
your issue. Thanks!

**Comment by darungon** [comment] 2017-09-20 15:50
Will there be a update for versiuon 1.11.2, currently major mods like ic2 and buildcraft run well on this, and this mod workes great with them, moving large amounts of cargo, oil tanker etc

**Comment by CalmBit** [comment] 2017-09-20 17:08
Duplicate of #171.

**Closed as completed** 2017-09-20 19:51 UTC
