### ISSUE TITLE
Post-rendering entity in world: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by rihlsul** [darkevilmac/archimedes-ships-plus#221] opened 2018-03-23 08:01 UTC
- Davincis Vessels v 1.12-6.340
- Moving World v 1.12-6.342
- Minecraft 1.12.2
- Forge 14.23.2.2624
- Crash report:  https://gist.github.com/rihlsul/276230e48114f5cf95d16fe3ed071c06

Built a large airship, towards the 2k mark, with 43% balloons.  All vanilla blocks, some blocks, some slabs, some stairs; with Davincis airblocks, a few passenger seats, and the helm.

It Assembled ok, but when mounting, it crashed.  The above log is from opening the world up after the crash.

Sadly, I don't have a built but pre-mounted world backup to submit for an example.

**Comment by darkevilmac** [comment] 2018-05-09 03:52
Duplicate of #223

**Closed as completed by darkevilmac** 2018-05-09 03:52 UTC
Labels: bug, duplicate, MovingWorld
