### ISSUE TITLE
Crash After Assembling

### ISSUE THREAD

**Issue by TechnologicApe** [darkevilmac/archimedes-ships-plus#183] opened 2017-08-27 22:25 UTC
After Assembling a Ship of any size, if I do anything, the game crashes. I've removed all mods and tested it. It still crashes.

Log:
https://gist.github.com/TechnologicApe/f4828a4ea14f407c38a65b904875eb20

**Comment by ChloeDawn** [comment] 2017-09-20 11:23
Duplicate of https://github.com/elytra/DavincisVessels/issues/179

**Closed as completed** 2017-09-21 19:18 UTC
