### ISSUE TITLE
Game Crashes When Put Steam Engine on Ship

### ISSUE THREAD

**Issue by ghost** [darkevilmac/archimedes-ships-plus#145] opened 2017-06-24 08:13 UTC
[crash-2017-06-24_11.12.20-server.txt](https://github.com/elytra/DavincisVessels/files/1099506/crash-2017-06-24_11.12.20-server.txt)

used forge 2351

**Comment by ghost** [comment] 2017-06-24 08:14
and ah, it also crashes while trying to rename the ship
[crash-2017-06-24_11.14.23-server.txt](https://github.com/elytra/DavincisVessels/files/1099509/crash-2017-06-24_11.14.23-server.txt)

**Comment by darkevilmac** [comment] 2017-06-24 08:17
Sounds like an issue with syncing ship data, is this on a dedicated server or just a client?

**Comment by ghost** [comment] 2017-06-24 08:21
just client

**Comment by darkevilmac** [comment] 2017-06-24 08:22
Hmm, can't reproduce that but did find a different issue. Going to fix that and see if that helps with your issue as it may be related.

**Comment by ghost** [comment] 2017-06-24 08:25
i hope it be fixed.

**Comment by darkevilmac** [comment] 2017-06-24 08:27
@kenijey attempt what you did with this MovingWorld build, https://ci.elytradev.com/job/elytra/job/MovingWorld/job/1.12/12/artifact/build/libs/movingworld-1.12-1.334-full.jar

**Comment by darkevilmac** [comment] 2017-06-24 08:30
Ah wait, I see what's wrong. The accesstransformer isn't being loaded. Forge may have implemented their signature checks.

**Comment by ghost** [comment] 2017-06-24 08:31
game won't even start with build 1.334.
you can reproduce

**Comment by ghost** [comment] 2017-06-24 08:34
and i just wonder why did you put the old texture to the secured bed(item)? there's new bed texture in 1.12 for inventory item.

**Comment by darkevilmac** [comment] 2017-06-24 08:41
> and i just wonder why did you put the old texture to the secured bed(item)? there's new bed texture in 1.12 for inventory item.

The secured bed item texture is different, the feet are a different colour. I bundle the old block textures so the old model will still work. I don't plan on making secured beds dyeable any time soon.

**Comment by ghost** [comment] 2017-06-24 08:42
no need for dyeable secured beds but you may select a unique texture for that bed. it would not be bad.
btw, forge is updated right now, you may want to see the changelog

**Comment by darkevilmac** [comment] 2017-06-24 08:45
Can you give me the error for the game crashing on the last build?

**Comment by ghost** [comment] 2017-06-24 08:46
[crash-2017-06-24_11.46.38-client.txt](https://github.com/elytra/DavincisVessels/files/1099532/crash-2017-06-24_11.46.38-client.txt)

**Comment by darkevilmac** [comment] 2017-06-24 08:52
It's not bunding Concrete....

**Comment by darkevilmac** [comment] 2017-06-24 09:55
@kenijey I'm off to bed, I've updated the builds on Curse. Give them a try and close the issue if your problem is resolved.

**Comment by ghost** [comment] 2017-06-24 10:12
hold on, should i install moving world library too?
if i should, it doesn't let me install both mods. it says mods are duplicated in your mods folder. (when i install devincis vessels + moving world)

**Comment by darkevilmac** [comment] 2017-06-24 10:15
Install both the recent builds of both mods on curse.

**Comment by ghost** [comment] 2017-06-24 10:24
okay it works fine now.
let me suggest a thing, can you add submarines? it would be lovely. you can add check for is the inside completely closed by outside.

**Comment by darkevilmac** [comment] 2017-06-24 19:34
Submarines are already in the mod. Please see the wiki.

**Closed as completed by darkevilmac** 2017-06-24 19:34 UTC
