### ISSUE TITLE
Dismounting ship throws user off the ship entity.

### ISSUE THREAD

**Issue by DeJayDev** [darkevilmac/archimedes-ships-plus#136] opened 2017-04-05 01:18 UTC
I have created a pretty little ship.

![Image of Ship](http://i.imgur.com/p0uAAHJ.png)

Assemble and mount the ship, have fun with the mod. It's a nice mod.

After a while, decide you've had enough ship. Press k to open the Ship Inventory. Disassemble ship.

![Image of Disassemble](http://i.imgur.com/psMh21g.png)

I was put up here, out of my seat. Same issue in survival, but this world is only water and I'm not trying to drown.

**Comment by budgej** [comment] 2017-04-25 22:56
I have the same issue.  I'm going to need enchanted boots to stop all this falling damage.

**Comment by DeJayDev** [comment] 2017-06-15 20:48
Highly requesting a response.

**Comment by exaskye** [comment] 2017-06-15 20:49
Seems like a dupe of #123. @darkevilmac?

**Comment by DeJayDev** [comment] 2017-06-15 20:51
Didn't know the elytra mention was a team. 🤔

**Comment by darkevilmac** [comment] 2017-06-16 00:24
I'll try and get a fix in the next version. It's just some bad math on my
part.

**Comment by darkevilmac** [comment] 2017-06-24 19:37
This is fixed if you disassemble the ship, if you don't there's nothing I can do.

**Closed as completed by darkevilmac** 2017-06-24 19:37 UTC
