### ISSUE TITLE
[Suggestion] 1.11.2 version?

### ISSUE THREAD

**Issue by SuperFanatic** [darkevilmac/archimedes-ships-plus#172] opened 2017-08-04 03:20 UTC
I mean, if your answer is no, then so be it. However, Is their a possibility of a 1.11.2 version? Most of the mods I use haven't been updated to 1.12 nor do I want to downgrade all of my stuff to 1.10. Again, if you don't want to do so then I can live without the mod. I just find it weird you didn't even have, like, a beta version for 1.11. you just skipped strait from 1.10 to 1.12. I'm not asking for the most bug-free, shiniest, most perfect version for 1.11.2, but one that runs at least. ...Please?

**Comment by darkevilmac** [comment] 2017-08-04 03:22
Duplicate of #171

**Closed as completed by darkevilmac** 2017-08-04 03:22 UTC
Labels: duplicate, invalid
