### ISSUE TITLE
LAN Multiplayer kicked out when Assembling a ship

### ISSUE THREAD

**Issue by 7red77** [darkevilmac/archimedes-ships-plus#125] opened 2016-12-17 01:18 UTC
I was trying the last build (1.10.2-0006) with my GF in my solo game via LAN when I assembled a ship and she got kicked out. So we tried a few time and everytime a ship got assembled, either I or her does it, she's getting kicked from the game with a fatal error message.

She can get back into the game and use the ships tho. So that's not a problem, but the assembly is.

Kinda weird :S
Thank you

**Comment by exaskye** [comment] 2016-12-17 01:21
Are you and your GF using the same versions of MovingWorld and DavincisVessels? A mismatch could cause something like this.

Please also post the error message to https://gist.github.com/ if it's text or https://imgur.com/ if it's an image. If the error is a "Disconnected from server" error, send your game output instead of a screenshot.

**Comment by 7red77** [comment] 2016-12-17 01:34
We are using the same version of both MW and DV and also same Forge version.
Also it can't really be a conflic with another mods since they're the only mods we got.

The only error message she got is "Connection Lost- A fatal error has occured, this connection is terminated", which isn't really helpful :|

**Comment by exaskye** [comment] 2016-12-17 01:34
That means the error was on the server-side. Send the server's logs/fml-server-latest.log if you have access to it. If all you have is the console that may work instead.

**Comment by 7red77** [comment] 2016-12-17 01:41
All I could find is that via the Game Output (Ninslayer is my GF):

[20:30:41] [Netty Server IO #3/ERROR]: java.lang.IndexOutOfBoundsException: readerIndex: 21 (expected: 0 <= readerIndex <= writerIndex(20))
[20:30:41] [Client thread/INFO]: [CHAT] Assembled !
[20:30:41] [Server thread/INFO]: Ninslayer lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[20:30:41] [Server thread/INFO]: Ninslayer left the game

**Comment by exaskye** [comment] 2016-12-17 01:43
This sounds like it is indeed a bug with the mod then. Could be related to it being a LAN server; does it still happen on a dedicated one? (Just running the server on your computer works.)

**Comment by 7red77** [comment] 2016-12-17 02:08
Might sounds stupid, but can't remember where the hell is the server client/launcher...

**Comment by exaskye** [comment] 2016-12-17 02:09
The server has no launcher, you need to run it manually from the command line. If you don't know how to do it don't worry about it.

**Comment by 7red77** [comment] 2016-12-17 02:18
never really work with minecraft servers.... sry

**Comment by darkevilmac** [comment] 2016-12-17 02:21
I need a log file posted to gist.github.com, that console snippet doesn't have enough info. Both the clients logs would be preferable.

**Comment by 7red77** [comment] 2016-12-17 02:33
Here's mine:
https://gist.github.com/7red77/08b9ca820a1eb66dd1c9c0a2ad215365

**Comment by 7red77** [comment] 2016-12-17 02:37
and hers:
https://gist.github.com/7red77/b702a9c28ef2b7dc2a2733688b367cbd

sorry for the delay

**Comment by foxfirecodes** [comment] 2017-01-12 14:44
Any news on this? I had the same problem playing with a friend. Not only did it kick him when I assembled my ship, it also kicked him a couple of times while just riding in the boat itself (he reconnected after it was assembled). We finally just settled on vanilla boats, which really sucks because I love this mod.

**Edit:** For your benefit I'll try and acquire some log files.

**Comment by AJstu** [comment] 2017-01-14 05:40
I had the same problem playing with my friend.Hope to fix it

**Comment by 7red77** [comment] 2017-01-14 14:22
Unfortunately, no update about this, but it was xmas and everything, so I guess they were busy too.

**Comment by foxfirecodes** [comment] 2017-01-14 14:38
I was digging through the code and the error makes no sense. *sigh*. This is really killing me because I **love** this mod for exploration. So much cooler than normal crappy vanilla boats.

**Comment by exaskye** [comment] 2017-01-15 10:06
If the error made sense, this would have been fixed 29 days ago. :P

**Comment by 7red77** [comment] 2017-01-15 16:06
XD

**Comment by darkevilmac** [comment] 2017-01-16 06:06
I hope to have this fixed in the 1.11 release, unfortunately I don't have a timeframe for that due to my computer needing repairs so I can't develop in my normal workspace.

**Comment by TimWaterham** [comment] 2017-02-12 22:19
If it helps, assembling a ship goes fine, mounting a ship will crash the client in my case on a dedicated server.

gave some rendering issues; got a crash report here
https://gist.github.com/TimWaterham/97b9da656f2eab0d6235f4085a6e7c04

If its unrelated just let me know, but it seems to be related as it occurs both on a type of server instance

Some details that ive figured out :
Does the same with or without optifine (only use it for shaders atm)
Works on SP world normally.
Any client in render range of the vessel crashes.
Server is fine registers no errors.

Edit : 
And yeah, its from a private pack.

**Comment by karikusa** [comment] 2017-04-05 15:53
Because there are many MODs that have not been upgraded to other MOD 1.11 yet if it is the environment of the multi-MOD server I am connected to, so it will be played in 1.10.2 for a while,
I hope it will be corrected in version 1.10.2 if possible ...

**Comment by lolmetimbers** [comment] 2017-06-19 09:31
Just experienced this bug yesterday where mounting a ship will cause everyone to be kicked out. Rarely it work. Not sure what the problem is. On 1.10.2

**Comment by darkevilmac** [comment] 2017-06-19 10:08
There's been no changes on this issue that have been corrected in official
releases. I don't know if this will be corrected in 1.10 as 1.12
development is almost complete and many developers seem to be focused on
developing for that version.

**Comment by darkevilmac** [comment] 2017-06-24 06:52
Should be fixed on 1.12

**Closed as completed by darkevilmac** 2017-06-24 06:52 UTC
