### ISSUE TITLE
vanishing ships completely need help would definitely appreciate it thanks  

### ISSUE THREAD

**Issue by ghost** [darkevilmac/archimedes-ships-plus#274] opened 2019-03-08 21:13 UTC
- The version of the mod I am using davincisvessels-1.12-6.340-full
- my Minecraft version 1.12.2
- my Forge version 14.23.5.2794
- The crash report or log however don't have one because it doesn't crash unfortunately however i do have pics of the build

hi it me crae a long loving fan of your mod even scene archimedes ship pre version i was building a ww2 custom air blimp for fun and i rain into problems with the build it seems to be when the ship get very large some reason and i don't know why so i went to the best people that would know the answer
here is a good look at the ship

here are the pics
this is to give you a good idea of the ship i am building

![2019-03-08_12 35 01](https://user-images.githubusercontent.com/37277242/54055430-ec35ce00-41a1-11e9-9162-2b9f39fbd210.png)

![2019-03-08_12 35 09](https://user-images.githubusercontent.com/37277242/54055433-edff9180-
41a1-11e9-88c2-bf216b63b3c5.png)

![2019-03-08_12 35 22](https://user-images.githubusercontent.com/37277242/54055436-ef30be80-
41a1-11e9-8c5d-05ca18c7c54c.png)

![2019-03-08_12 35 27](https://user-images.githubusercontent.com/37277242/54055438-f061eb80-41a1-11e9-9213-eec70e4c014e.png)

![2019-03-08_12 35 46](https://user-images.githubusercontent.com/37277242/54055439-f1931880-41a1-11e9-8fba-a7eefac8ebb4.png)

![2019-03-08_12 35 52](https://user-images.githubusercontent.com/37277242/54055443-f2c44580-41a1-11e9-8f87-c90b3a2881b2.png)

![2019-03-08_12 35 57](https://user-images.githubusercontent.com/37277242/54055444-f35cdc00-41a1-11e9-9f74-d5431660b8b4.png)

![2019-03-08_12 36 05](https://user-images.githubusercontent.com/37277242/54055445-f48e0900-41a1-11e9-9722-285295a305b3.png)
![2019-03-08_12 36 11](https://user-images.githubusercontent.com/37277242/54055446-f5269f80-41a1-11e9-9040-686d9388c660.png)

![2019-03-08_12 36 32](https://user-images.githubusercontent.com/37277242/54055447-f657cc80-41a1-11e9-8239-44af88d7a1dc.png)

![2019-03-08_12 36 39](https://user-images.githubusercontent.com/37277242/54055450-f788f980-41a1-11e9-84fd-e5d4fd799441.png)

![2019-03-08_12 36 52](https://user-images.githubusercontent.com/37277242/54055451-f8219000-41a1-11e9-9fc5-5e29cddfad6b.png)

now a play by play what happens 
 left click the ships helm
![2019-03-08_12 36 08](https://user-images.githubusercontent.com/37277242/54055507-256e3e00-41a2-11e9-905a-51ce4d737349.png)

left click the ships helm and then click the  assemble ship gui this will give you an idea of the size of the ship
![2019-03-08_12 36 11](https://user-images.githubusercontent.com/37277242/54055593-68301600-41a2-11e9-92bd-b3d91cb5e8e7.png)

then get in the ship
![2019-03-08_12 37 11](https://user-images.githubusercontent.com/37277242/54055526-36b74a80-41a2-11e9-9cac-81c57b408505.png)

mounts the ship "time of the glitch"
![2019-03-08_12 37 20](https://user-images.githubusercontent.com/37277242/54055651-90b81000-41a2-11e9-8d71-7c89b04ca120.png)

does not crash and click shift
![2019-03-08_12 37 25](https://user-images.githubusercontent.com/37277242/54055683-a9282a80-41a2-11e9-90ca-9f1623708401.png)

**Comment by ghost** [comment] 2019-03-08 21:16
keep in mind that i set the config  to this that is why it is able to fly 
[New Text Document (2).txt](https://github.com/TridentMC/DavincisVessels/files/2947488/New.Text.Document.2.txt)

**Comment by ghost** [comment] 2019-03-08 21:18
even an explanation will help a lot

**Comment by ghost** [comment] 2019-03-08 21:20
brain flash does it have to do with the build being over 1 chunk size because if that the case it would be 2 chunks long

**Comment by ghost** [comment] 2019-03-08 21:21
just thinking

**Comment by ghost** [comment] 2019-03-08 21:22
and i am only using 3 mod in the build so i don't think that would be a problem

**Comment by ghost** [comment] 2019-03-08 21:40
and i have been noticing you haven't been answering these type of problems

**Comment by ghost** [comment] 2019-03-08 21:41
why is that

**Comment by darkevilmac** [comment] 2019-03-08 22:20
Duplicate of #233

**Closed as completed by darkevilmac** 2019-03-08 22:20 UTC

**Comment by ghost** [comment] 2019-03-08 22:25
found a fix it is your render distance rase it  wtf why that's a thing but it works
