### ISSUE TITLE
Texture error if mounting the ships when shaders opened in 1.12

### ISSUE THREAD

**Issue by JayCkie** [darkevilmac/archimedes-ships-plus#177] opened 2017-08-08 14:17 UTC
DavincisVessels : 1.12-3.332-full , 1.12-4.334-full , 1.12-5.335-full
MovingWorld : 1.12-4.340-full
Forge : 14.21.1.2443
Optifine : 1.12_HD_U_C5

here's the video about the bug
https://youtu.be/n_buAm23Gb8

**Comment by exaskye** [comment] 2017-08-08 14:20
Does it work if you disable VBOs?

Also it's nearly impossible to read your log in the video. Please post it to [Gist](https://gist.github.com/).

**Comment by JayCkie** [comment] 2017-08-08 14:29
![2017-08-08_22 24 04](https://user-images.githubusercontent.com/30834172/29076628-a8dd51c6-7c88-11e7-8870-feea3dfd7c58.png)

Umm...I don't know how to describe this.
But at least it's better now,thanks for your help!

**Comment by exaskye** [comment] 2017-08-08 14:30
Since disabling VBOs fixes it, this is duplicate of #164.

**Closed as completed by exaskye** 2017-08-08 14:30 UTC

**Comment by darkevilmac** [comment] 2017-08-08 21:13
Ugh, making a fix to MovingWorld to put an end to this.
