### ISSUE TITLE
Anchor is not working (1.7.10)

### ISSUE THREAD

**Issue by PumaBlack** [darkevilmac/archimedes-ships-plus#63] opened 2015-12-03 14:28 UTC
Hi, thanks for your work on this outstanding mod! But i have an issue with the anchor point.

I place one on the ground, on on the ship. Right click one the ground anchor (now it is set) and shift-right-click on a ship-anchor, also set.

Bur if i try to align, nothing happens, no "snap-into-possition", i just got my ship back into the world-grid, but not aligned to the anchor, even if i only to blocks away.

Is that my fault or an issue?

Thanks in advance.

**Comment by iRhuel** [comment] 2016-01-08 22:21
Are you aligning, or disassembling? They're very different. Aligning doesn't place the ship blocks back into the world, only aligns it with a previously configured anchor set. The key is set to EQUALS by default I think. You can hold it to align almost perfectly, then disassemble in the exact spot you built on.

**Comment by darkevilmac** [comment] 2016-01-09 00:00
Woops, looks like this got pushed back in my email and I missed it, iRhuel has the right idea. I'll make a quick video in the near future for the wiki to show how to use the Anchor Point properly.

**Comment by iRhuel** [comment] 2016-01-09 22:27
@darkevilmac I could help you rewrite some of the item descriptions so that they're more verbose if you're willing.

**Comment by darkevilmac** [comment] 2016-01-10 01:52
The wiki is there just for that reason, you should be able to edit it by default if you can't I'll add some permissions for you.

**Comment by PumaBlack** [comment] 2016-01-12 20:55
After all i figured out how it works! BUT there is a major issue, that crashes the game! You can read that in the wiki, i replaced the old entry with a new one.

Instead of aling the ancors ontop of each other, they should aling relative to each other. If the anchors are set up, the system saves both positions, from the ground anchor and the ships anchor. If  we aling, the ships anchor snaps into the same position as we set it up.

Thanks for your work and keep this great mod up! I love it!

**Comment by PumaBlack** [comment] 2016-01-12 21:36
at least, english is not my native language, you may corrcet my worse grammar and vocabolary ^^

**Comment by pyrodogg** [comment] 2016-01-29 18:35
Related to the title of the issue, the anchor only seems to work if you use the assigned hotkey. It doesn't work if you use the gui and click the Align button.

**Comment by darkevilmac** [comment] 2016-02-11 11:39
Closing as I'm unable to reproduce the issue.

**Closed by darkevilmac** 2016-02-11 11:39 UTC
