### ISSUE TITLE
(1.8.9) Crash when trying to mount ship

### ISSUE THREAD

**Issue by Kiyaku** [darkevilmac/archimedes-ships-plus#68] opened 2016-01-29 11:22 UTC
Assembling worked fine but as soon as i click to mount it, it crashes my game (and i can't load it anymore, keeps crashing). 

Crashlog: http://pastebin.com/C53frzp0 

Let me know if you need more info!

**Comment by Jantje-NL** [comment] 2016-02-09 19:37
I have the same problem. But i discoverd that when i remove the passenger seats from the ship  it works. maybe you can try to remove them?

**Comment by darkevilmac** [comment] 2016-02-11 11:42
Will take a look soon.

**Comment by darkevilmac** [comment] 2016-02-24 04:18
Forgot about this entirely sorry, taking a look right now, looks like a simple fix.

**Comment by Jantje-NL** [comment] 2016-02-24 14:16
Cool. Cant wait for it to work ^^

**Comment by sblectric** [comment] 2016-02-26 00:50
same

**Comment by darkevilmac** [comment] 2016-02-26 00:51
Is this still occuring in the current versions?

**Comment by sblectric** [comment] 2016-02-26 00:58
yep just happened

**Comment by midniteoftherose** [comment] 2016-02-28 03:17
Server Crash Log: http://hastebin.com/gawumuhifi.vhdl
using the 
archimedesshipsplus-MC1.8.9-INDEV-D
movingworld-MC1.8.9-INDEV-E-full
1.8.9 minecraft

**Comment by midniteoftherose** [comment] 2016-02-28 19:12
anything new?

**Comment by darkevilmac** [comment] 2016-02-28 20:24
Hi, I've been working/sick the past few days I'll look in an hour or so. :)

**Comment by midniteoftherose** [comment] 2016-02-29 22:32
just checking up :)

**Comment by midniteoftherose** [comment] 2016-02-29 22:33
also leaving some info that the mod seems to be completely broken now, as it wont assemble a ship in singleplayer anymore...

**Comment by midniteoftherose** [comment] 2016-02-29 22:33
it wont crash or anything but it just doesnt do it
ill try to make a vid for you

**Comment by Jantje-NL** [comment] 2016-03-03 18:32
It stil doesnt work for me. with the newest versions of the mod it wont assamble at all. if i try using different versions of the mods it does the same. when i try using. archimedes ships plus-MC1.8.9-INDEV-B.jar It assambles the ship and it works, but when i put a passenger seat on the ship and then want to assamble it crashes the game.
[crash-2016-03-03_19.18.50-server.txt](https://github.com/darkevilmac/archimedes-ships-plus/files/157417/crash-2016-03-03_19.18.50-server.txt)

**Comment by midniteoftherose** [comment] 2016-03-04 10:16
im waiting to see if theres a new one out since the release of 1.9 so im just gonna be patient, and thanks again for your excellent mod

**Comment by darkevilmac** [comment] 2016-03-04 10:43
Hi all!

Currently waiting on 1.9's release from forge. Until then I'm on a short
hiatus, I don't expect forge to take more than a week or so.

**Comment by midniteoftherose** [comment] 2016-03-04 18:02
not a prob :) like  i said, i figured with 1.9 no point in waiting on a fix for this when this can simply just be a bug you can implement a fix in the newest one with

**Comment by darkevilmac** [comment] 2016-03-06 04:44
1.9 is taking a bit longer than I had anticipated so I'm gonna do some testing and see what I can do. Thanks for your patience everyone.

**Comment by darkevilmac** [comment] 2016-03-06 04:52
Give these builds a try ASAP, thanks!

https://up1.ca/#Ph3rVQ-HG_7ARqpV1r5Llg
https://up1.ca/#uPbg6t_twoK_IWURWGkTdw

**Comment by Jantje-NL** [comment] 2016-03-06 08:43
when i click the download button it doesnt do annything

**Comment by midniteoftherose** [comment] 2016-03-06 22:41
checking it out now

**Comment by midniteoftherose** [comment] 2016-03-07 00:44
so far seems to work for single player, my comp went buggy for my server tho so give me some time to check and ill get back to you :)

**Comment by midniteoftherose** [comment] 2016-03-07 02:50
what forge is this supposed to work with  btw?

**Comment by midniteoftherose** [comment] 2016-03-07 04:45
[http://plays.tv/video/56dd06c9093fe19522](url)
thanks again!!! this is for you darkevilmac!

**Comment by midniteoftherose** [comment] 2016-03-07 16:39
[http://plays.tv/s/KhqihF2FB_Oy](url)

**Comment by Jantje-NL** [comment] 2016-03-07 18:49
mounting the ship works again. But when i try it with a passenger seat it still keeps crashing the game and the save file breaks so i cant use the world annymore. ( thank god i have backups) ;) ive added the crash log
[crash-2016-03-07_19.43.52.txt](https://github.com/darkevilmac/archimedes-ships-plus/files/161885/crash-2016-03-07_19.43.52.txt)

**Comment by Jantje-NL** [comment] 2016-03-07 18:53
@midniteoftherose Can you try it with a passenger seat on the ship? but be carefull, make a backup of your world cause mine keeps crashing when i have a passenger seat on the ship. im wondering of others have the same problem.

**Comment by darkevilmac** [comment] 2016-03-07 21:48
@midniteoftherose don't bother doing what he said to try, I'm working taking a look right now and will try and get a build out by the end of the day.

**Comment by darkevilmac** [comment] 2016-03-07 22:09
I *think* I've found the root cause of the problem, some stupid code I was messing around with was left over/I was up at 3AM and it seemed like a good idea at the time.

**Comment by darkevilmac** [comment] 2016-03-07 22:10
http://i.imgur.com/QNb48sp.png 

Everything seems to be working now.

Pay no attention to the transparent purple triangle it's of no concern.

**Comment by midniteoftherose** [comment] 2016-03-07 23:18
soooooo everything is jolly good?
1

**Closed** 2016-03-08 08:07 UTC
Labels: bug
